name: Test
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout local action 
        uses: actions/checkout@v3.3.0
      - name: Say hello
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@octocat'
