name: Test
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout local action 
        uses: actions/checkout@main
        
      - name: Say hello
        uses: ./.github/actions/hello-world-docker-action@v1
        with:
          who-to-greet: '@octocat'
